version: '3.6'
services:

  db:
    build: ./db
    image: theca.cash/theca-mysql
    container_name: theca-mysql
    volumes:
      - ${DATABASE_PATH}:/var/lib/mysql
    environment:
      TZ: ${TZ}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password
<<<<<<< HEAD
    #command: mysqld --event_scheduler="ON"
=======
    networks:
      - ${DOCKER_NETWORK_NAME}
    command: mysqld --event_scheduler="ON"
>>>>>>> 24d67d269a35546cef810dde9ef715c075d4db18
    secrets:
      - mysql_root_password

  memcache:
    build: ./memcache
    image: theca.cash/theca-cache
    container_name: theca-cache

  sync:
    build: ./sync
    image: theca.cash/theca-sync
    container_name: theca-sync
    depends_on:
      - db
<<<<<<< HEAD
=======
    networks:
      - ${DOCKER_NETWORK_NAME}
>>>>>>> 24d67d269a35546cef810dde9ef715c075d4db18
    restart: always

  web:
    build: ./web
    image: theca.cash/theca-webserver
    container_name: theca-webserver
    volumes:
      - ./web/web/:/var/www/
    environment:
     - TZ=${TZ}
     - MEMCACHE_HOSTNAME=${MEMCACHE_HOSTNAME}
     - MEMCACHE_PORT=${MEMCACHE_PORT}
     - DATABASE_NAME=${DATABASE_NAME}
     - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
     - DATABASE_PORT=${DATABASE_PORT}
     - DATABASE_USERNAME=${DATABASE_USERNAME}
     - DATABASE_PASSWORD=DOCKERSECRET:database_password
    ports:
      - "8080:8000"
    secrets:
      - database_password
  run-theca-client:
    build: ./run-client
    image: theca.cash/run-theca-client
    container_name: run-theca-client
    volumes:
      - ./build-client/build:/build
    environment:
      - TZ=${TZ}
      - INTERNAL_WEBSERVER=${WEBSERVER_HOSTNAME}
      - INTERNAL_PORT_WEBSERVER=${INTERNAL_PORT_WEBSERVER}
      - INTERNAL_PORT_RUN_THECA_CLIENT=${INTERNAL_PORT_RUN_THECA_CLIENT}
<<<<<<< HEAD
=======
    networks:
      - ${DOCKER_NETWORK_NAME}
>>>>>>> 24d67d269a35546cef810dde9ef715c075d4db18

secrets:
  database_password:
    file: secrets/database_password.txt
  mysql_root_password:
    file: secrets/mysql_root_password.txt

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.12.0/24
      #      thecanet:
      #external: true
