version: "3"
services:

  db:
    build: ./db
    environment:
        MYSQL_ROOT_PASSWORD: 8drRNG8RWw9FjzeJuavbY6f9
    networks:
      thecanet:
        ipv4_address: 192.168.12.2
    command: mysqld --event_scheduler="ON"

  memcache:
    build: ./memcache
    networks:
      thecanet:
        ipv4_address: 192.168.12.3

  sync:
    build: ./sync
    depends_on:
      - "db"
        #stdin_open: true
        #tty: true
#    network_mode: bridge
    networks:
      thecanet:
        ipv4_address: 192.168.12.4
    restart: always

  web:
    build: ./web
    volumes:
      - ./web/web/:/var/www/
    ports:
      - "127.0.0.1:8080:8000"
    networks:
      thecanet:
        ipv4_address: 192.168.12.5

networks:
  thecanet:
    external: true
