version: "3"
services:

  db:
    build: ./db
    environment:
        MYSQL_ROOT_PASSWORD: 8drRNG8RWw9FjzeJuavbY6f9
    networks:
      thecanet:
        ipv4_address: 192.168.11.2

  memcache:
    build: ./memcache
    networks:
      thecanet:
        ipv4_address: 192.168.11.3

  sync:
    build: ./sync 
    depends_on:
      - "db"
        #stdin_open: true
        #tty: true
    networks:
      thecanet:
        ipv4_address: 192.168.11.4

  web:
    build: ./web
    volumes:
      - ./web/web/:/usr/share/nginx/html/
    ports:
      - "127.0.0.1:80:80"
    networks:
      thecanet:
        ipv4_address: 192.168.11.5

networks:
  thecanet:
    external: true

