version: "3"
services:

  db:
    build: ./db
    environment:
        MYSQL_ROOT_PASSWORD: 8drRNG8RWw9FjzeJuavbY6f9

  memcache:
    build: ./memcache

  sync:
    build: ./sync 
    stdin_open: true
    tty: true

  web:
    build: ./web
    volumes:
      - ./web/web/:/usr/share/nginx/html/
    ports:
      - "127.0.0.1:80:80"
